### ISSUE TITLE
script/run.sh does not exist (Install failed)

### ISSUE THREAD

**Issue by coolpixgnu** [NaveenRudra/RTTM#10]
Hi,

Step 12/24 : ADD script/run.sh /usr/local/bin/run.sh
ADD failed: stat /var/snap/docker/common/var-lib-docker/tmp/docker-builder151664376/script/run.sh: no such file or directory

**Comment by yogevmi** [comment]
Hi,
I also had the same problem, just found it in the history version:
https://raw.githubusercontent.com/NaveenRudra/RTTM/9ca5259676e186ba745810aa152e0e73ad8bac2b/script/run.sh

**Comment by coolpixgnu** [comment]
Hi @yogevmi  

I just solved creating an empty file "/script/run.sh", and later works well.

Hope this help.

Kind regards

**Comment by NaveenRudra** [comment]
Thanks for reporting this issue. It has been fixed.
