### ISSUE TITLE
how to run your images

### ISSUE THREAD

**Issue by hahadaxia** [NaveenRudra/RTTM#11]
I have build the Dockerfile .

but do not konw how to run from the image.

**Comment by NaveenRudra** [comment]
Make sure you have docker installed first.
Follow the steps mentioned in https://real-time-threat-monitoring.readthedocs.io/en/latest/setupGuide.html

**Comment by hahadaxia** [comment]
yes ,i got the step
execute docker build .
Run docker exec -it <container id> /bin/bash

but there is no cmd that run the docker from image

**Comment by hahadaxia** [comment]
> Make sure you have docker installed first.
> Follow the steps mentioned in https://real-time-threat-monitoring.readthedocs.io/en/latest/setupGuide.html
yes ,i got the step
execute docker build .
Run docker exec -it /bin/bash

but there is no cmd that run the docker from image
